# Generated by Django 6.0 on 2025-12-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('grain', 'Grain')], default='fruit', max_length=20),
        ),
    ]
